DROP DATABASE IF EXISTS faculty;

CREATE DATABASE faculty;

use faculty;

CREATE TABLE users(
id INTEGER PRIMARY KEY  AUTO_INCREMENT,
email VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(30) NOT NULL,
role VARCHAR(20),
status BOOLEAN
);

CREATE TABLE course(
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
progress VARCHAR(30) NOT NULL
);

CREATE TABLE schedule(
id INTEGER PRIMARY KEY,
id_course INT,
id_user INT,
mark INT,
FOREIGN KEY (id_course) REFERENCES course(id)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (id_user) REFERENCES users(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO users VALUES(DEFAULT, 'email', 'pa', 'rab', true);

SELECT * FROM users;
